services:
  lb:
    volumes:
      - ./haproxy.profile.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sockets:/sockets
  api1:
    build:
      target: profile
  api2:
    build:
      target: profile
