services:
  lb:
    image: lobomfz/rinha-2026-bun-lb:v1
    ports:
      - '9999:9999'
    environment:
      PORT: 9999
      UPSTREAMS: /sockets/api1.sock,/sockets/api2.sock
    volumes:
      - sockets:/sockets
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: '20MB'
    cpus: 0.20
    mem_limit: 20m

  api1: &api
    image: lobomfz/rinha-2026-bun-api:v1
    environment:
      SOCK_PATH: /sockets/api1.sock
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: '0.40'
          memory: '165MB'
    cpus: 0.40
    mem_limit: 165m

  api2:
    <<: *api
    environment:
      SOCK_PATH: /sockets/api2.sock

volumes:
  sockets:
