services:
  lb:
    build:
      context: ./load-balancer
      target: prod
    ports:
      - '9999:9999'
    volumes:
      - sockets:/sockets
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: '20MB'
    cpus: 0.20
    mem_limit: 20m

  api1: &api
    build:
      context: .
      target: prod
    environment:
      SOCK_PATH: /sockets/api1.sock
      FINE_COUNT: ${FINE_COUNT:-}
      FINE_PROBE: ${FINE_PROBE:-}
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: '0.40'
          memory: '165MB'
    cpus: 0.40
    mem_limit: 165m

  api2:
    <<: *api
    environment:
      SOCK_PATH: /sockets/api2.sock
      FINE_COUNT: ${FINE_COUNT:-}
      FINE_PROBE: ${FINE_PROBE:-}

volumes:
  sockets:
